### ISSUE TITLE
The source archive uploaded to pypi does not contain the header files

### ISSUE THREAD

**Issue by jan-janssen** [nomad-coe/matid#19]
The files:
```
matid/ext/celllist.h
matid/ext/geometry.h
```
are missing in https://files.pythonhosted.org/packages/e0/cc/bb3feb713f7346e8b7dcab15975e9b24cfac198e037e3097d2f804d42cda/matid-2.0.0.tar.gz

**Comment by lauri-codes** [comment]
Hi @jan-janssen! You are right. Somehow this slipped past. I will make a patch release.

**Comment by lauri-codes** [comment]
There is now a new release: v2.0.1 with the header files included.

**Comment by jan-janssen** [comment]
perfect - this fixed the conda package https://github.com/conda-forge/matid-feedstock/pull/11
